# Generated by Django 3.0.8 on 2020-08-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('RegisterNumber', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sem1',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Main')),
                ('EngineeringPhysics', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('EngineeringMathematics', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('EngineeringChemistry', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('EngineeringGraphics', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('CommunicativeEnglish', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ProgramSolvingAndPythonProgramming', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
            ],
        ),
    ]
