# Generated by Django 3.0.8 on 2020-08-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sem1',
        ),
    ]
