# Generated by Django 3.0.8 on 2020-08-04 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_sem1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem1',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Main')),
                ('EngineeringPhysics', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('EngineeringMathematics', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('EngineeringChemistry', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('EngineeringGraphics', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('CommunicativeEnglish', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ProgramSolvingAndPythonProgramming', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ProgramSolvingAndPythonProgrammingLaboratory', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('PhysicsandChemistryLaboratory', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sem2',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Main')),
                ('TechnicalEnglish', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('EngineeringMathematicsII', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('MaterialsScience', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('EnvironmentalScienceandEngineering', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('EngineeringMechanics', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('EngineeringPracticesLaboratory', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('BasicElectricalElectronicsandInstrumentationEngineering', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
            ],
        ),
    ]
