# Generated by Django 3.0.8 on 2020-08-06 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_sem1_sem2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem3',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Main')),
                ('TransformsandPartialDifferentialEquations', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('EngineeringThermodynamics', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('FluidMechanicsandMachinery', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ManufacturingTechnologyI', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ElectricalDrivesandControls', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ManufacturingTechnologyLaboratoryI', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ComputerAidedMachineDrawing', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ElectricalEngineeringLaboratory', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('InterpersonalSkillsListeningSpeaking', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
            ],
        ),
    ]
