# Generated by Django 3.0.8 on 2020-08-06 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_sem3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem4',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Main')),
                ('StatisticsandNumericalMethods', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('KinematicsofMachinery', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ManufacturingTechnologyII', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('EngineeringMetallurgy', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('StrengthofMaterialsforMechanicalEngineers', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ThermalEngineeringI', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ManufacturingTechnologyLaboratoryII', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('StrengthofMaterialsandFluidMechanicsandMachineryLaboratory', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('AdvancedReadingandWriting', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sem5',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Main')),
                ('ThermalEngineeringII', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('DesignofMachineElements', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('MetrologyandMeasurements', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('DynamicsofMachines', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('OpenElectiveI', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('KinematicsandDynamicsLaboratory', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ThermalEngineeringLaboratory', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('MetrologyandMeasurementsLaboratory', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sem6',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Main')),
                ('DesignofTransmissionSystems', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ComputerAidedDesignandManufacturing', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('HeatandMassTransfer', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('FiniteElementAnalysis', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('HydraulicsandPneumatics', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ProfessionalElectiveI', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('CADCAMLaboratory', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('DesignandFabricationProject', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ProfessionalCommunication', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sem7',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Main')),
                ('PowerPlantEngineering', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ProcessPlanningandCostEstimation', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('Mechatronics', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('OpenElectiveII', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ProfessionalElectiveII', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ProfessionalElectiveIII', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('SimulationandAnalysisLaboratory', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('MechatronicsLaboratory', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('TechnicalSeminar', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sem8',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Main')),
                ('PrinciplesofManagement', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ProfessionalElectiveIV', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
                ('ProjectWork', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('RA', 'Arrear')], max_length=2)),
            ],
        ),
    ]
